1|Git-Aliases|Git-Aliases.sh
2|Git-Fork|Git-Fork.sh
3|Git-LinkRepo|Git-LinkRepo.sh
4|Git-Login|Git-Login.sh
5|Git-Merge|Git-Merge.sh
6|Git-Push|Git-Push.sh
7|Git-Release|Git-Release.sh
8|Git-Statistic|Git-Statistic.sh