# Versions.
Git_Scripts_Version=8.2.0
Git_Aliases_Version=2.1.0
Git_Launcher_Version=4.1.0
Git_LinkRepo_Version=3.2.0
Git_Login_Version=3.1.0
Git_Merge_Version=2.2.0
Git_Push_Version=4.1.0
Git_Release_Version=2.1.0
Git_Statistic_Version=2.2.0
