# Versions.
Git_Scripts_Version=9.0.0

Git_Aliases_Version=2.2.1
Git_Fork_Version=1.0.0
Git_Launcher_Version=4.3.0
Git_LinkRepo_Version=3.4.0
Git_Login_Version=3.2.1
Git_Merge_Version=2.4.0
Git_Push_Version=4.3.0
Git_Release_Version=2.2.1
Git_Statistic_Version=2.3.1
