# Versions.
Git-Scripts_Version="6.7.0"
Git-Launcher_Version="2.3.0"
Git-Push_Version="3.1.0"
Git-Link-Repo_Version="2.1.0"
Git-Release_Version="1.4.0"
Git-Merge_Version="1.2.0"
Git-Login_Version="2.1.0"
Git-Aliases_Version="1.1.0"
