# Versions.
Git_Scripts_Version=10.0.0

Git_Aliases_Version=3.0.0
Git_Fork_Version=3.0.0
Git_Launcher_Version=5.0.0
Git_LinkRepo_Version=4.0.0
Git_Login_Version=4.0.0
Git_Merge_Version=3.0.0
Git_Push_Version=5.0.0
Git_Release_Version=3.0.0
Git_Statistic_Version=3.0.0