# Versions.
Git_Scripts_Version=10.17.0

Git_Aliases_Version=3.3.2
Git_Fork_Version=3.5.0
Git_Launcher_Version=5.3.2
Git_LinkRepo_Version=6.5.0
Git_Login_Version=5.2.2
Git_Merge_Version=3.6.0
Git_Push_Version=6.5.0
Git_Release_Version=4.0.1
Git_Statistic_Version=3.3.2

# Other.
Executable=*.sh *.py *.bash *.zsh *.pl *.rb *.lua *.mjs *.cjs
