# Versions.
Git_Scripts_Version=11.3.0

Git_Bashrc_Version=4.1.1
Git_Fork_Version=3.5.1
Git_Launcher_Version=5.3.3
Git_LinkRepo_Version=6.5.2
Git_Login_Version=5.2.3
Git_Merge_Version=3.6.3
Git_Release_Version=4.0.2
Git_Statistic_Version=3.3.3
Git_Sync_Version=6.7.0

# Other.
Executable=*.sh *.py *.bash *.zsh *.pl *.rb *.lua *.mjs *.cjs
