# Versions.
Git_Scripts_Version=10.16.1

Git_Aliases_Version=3.3.1
Git_Fork_Version=3.4.1
Git_Launcher_Version=5.3.1
Git_LinkRepo_Version=6.4.1
Git_Login_Version=5.2.1
Git_Merge_Version=3.5.1
Git_Push_Version=6.4.1
Git_Release_Version=4.0.0
Git_Statistic_Version=3.3.1

# Other.
Executable=*.sh *.py *.bash *.zsh *.pl *.rb *.lua *.mjs *.cjs
